apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app   # Label selector to match pods with the "app: nodejs-app" label
  ports:
    - name: http
      protocol: TCP
      port: 80         # Port exposed on the service
      targetPort: 4000 # Port your Node.js app is running on in the pod
  type: LoadBalancer 

