apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: rivkyschon/nodejs-app:0.0.3  # Use the image you pushed to a container registry
        ports:
        - containerPort: 4000  # Adjust the port as needed
